title: <p style="font-size:30px;font-style:italic;">Turning Data into Actionable, Understadable, & Cheerful Insights</p>
description: <p style="font-size:25px;">Hend Abd El-Ghafour</p> <p style="font-size:20px;font-style:italic;">Data Analyst </p>
show_downloads: true
theme: jekyll-theme-cayman
github:
  zip_url: <a href="https://github.com/hend-a-ghafour/hend-a-ghafour.github.io/blob/171e9aebaec6231c77f22fb673b599eed52d8dc9/files/Hend_Abdelghafour_Resume.pdf" download>Download Resume</a>
