title: <center><span style="color:#243444"> Hend <br> Abd El-Ghafour</span></center>
logo: /Media/Profile Pic.jpg 
description: <h1><center><strong> <em><span style="color:#7c7959"> Data Analyst </span></em></Strong> </center></h1> <br> <a href="https://github.com/hend-a-ghafour/hend-a-ghafour.github.io/blob/main/Media/Hend%20Abd%20El-Ghafour-%20Resume.pdf">    ðŸ“„ Download My CV</a>
show_downloads: true
theme: jekyll-theme-minimal


