title: <p style="font-size:30px;font-family: "Georgia";font-style:italic;">Turning Data into Actionable, Understadable, & Cheerful Insights</p>
logo: /Media/Profile Pic.jpg 
description: <p style="font-size:25px;">Hend Abd El-Ghafour - Data Analyst </p>
show_downloads: true
theme: jekyll-theme-cayman


