title: <p style="font-size:30px;font-style:italic;">Turning Data into Actionable, Understadable, & Cheerful Insights</p>
description: <p style="font-size:25px;">Hend Abd El-Ghafour</p> <br> <p style="font-size:20px;font-style:italic;">Data Analyst </p><br><a href=" https://drive.google.com/uc?export=download&id=1xUyTtIILk3J_hld7wWpgDHSRVs6Er9ew"> â¤“ Resume</a>
show_downloads: false
theme: jekyll-theme-cayman


