title: <p style="font-size:30px;font-style:italic;">Turning Data into Actionable, Understadable, & Cheerful Insights</p>
description: <p style="font-size:25px;">Hend Abd El-Ghafour</p> <p style="font-size:20px;font-style:italic;">Data Analyst </p>
show_downloads: true
theme: jekyll-theme-cayman
github:
  zip_url: <a href="https://drive.google.com/file/d/1xUyTtIILk3J_hld7wWpgDHSRVs6Er9ew/view?usp=sharing" class="btn">Download Resume</a>
