title: <p style="font-size:30px;font-style:italic;">Turning Data into Actionable, Understadable, & Cheerful Insights</p>
description: <p style="font-size:25px;">Hend Abd El-Ghafour</p> <br> <p style="font-size:20px;font-style:italic;">Data Analyst 
show_downloads: false
theme: jekyll-theme-cayman


