title: <p style="font-size:30px;font-style:italic;">Turning Data into Actionable, Understadable, & Cheerful Insights</p>
description: <p style="font-size:25px;">Hend Abd El-Ghafour</p> <br> <p style="font-size:20px;font-style:italic;">Data Analyst </p><br><a href=" https://drive.google.com/uc?export=download&id=1xUyTtIILk3J_hld7wWpgDHSRVs6Er9ew" style="display:inline-block; padding:1rem; color:rgba(255, 255, 255, 0.7); background-color: rgba(255, 255, 255, 0.08);border-color:rgba(255, 255, 255, 0.02); text-align:center; border-radius:0.3rem;width: 130px; height: 60px;font-size:1rem;margin-top:1rem;padding-left:0rem;padding-right:0rem;"> â¤“ Resume</a>
show_downloads: false
theme: jekyll-theme-cayman


