title: <p style="font-size:30px;font-style:italic;">Turning Data into Actionable, Understadable, & Cheerful Insights</p>
description: <p style="font-size:25px;">Hend Abd El-Ghafour</p> <p style="font-size:20px;font-style:italic;">Data Analyst </p>
show_downloads: true
theme: jekyll-theme-cayman
github:
  zip_url: github.zip_url
  another_url: https://github.com/hend-a-ghafour/hend-a-ghafour.github.io/blob/main/files/Hend_Abdelghafour_Resume.pdf


