title: <p style="font-size:40px;">Hend Abd El-Ghafour</p>
logo: /Media/Profile Pic.jpg 
description: <p style="color:#ffffff; font-size:18px;">Data Analyst </p>
show_downloads: true
theme: jekyll-theme-architect


