title: <center><span style="color:#243444"> Hend <br> Abd El-Ghafour</span></center>
logo: /Media/Profile Pic.jpg
description: <h1><center><strong> <em><span style="color:#7c7959"> Data Analyst </span></em></Strong> </center></h1>
show_downloads: true
theme: jekyll-theme-minimal


